### ISSUE TITLE
Slider can get stuck in drag-mode when releasing over a "disabled" element.

### ISSUE THREAD

**Issue by jgerigmeyer** [leongersen/noUiSlider#476] opened 2015-07-09 19:12 UTC
Because the ``mouseup`` event does not fire on ``disabled`` elements, the slider can get stuck in "drag" mode and the event listeners are not removed. To reproduce, drag a slider and release the mouse while hovering on a ``disabled`` element somewhere on the page.

**Comment by leongersen** [comment] 2015-07-10 20:44
Could you set up an example? I can't reproduce this.

**Comment by jgerigmeyer** [comment] 2015-07-13 15:15
https://jsfiddle.net/jgerigmeyer/pm60pp6x/1/

If you drag the slider and release while hovering over the ``disabled`` button, then move your mouse around the slider is stuck in "drag" mode.

Interestingly, this is also true if you release in one of the other JSFiddle "frames". So I'm not sure what's causing the underlying bug here. I can try to look into it more.

**Comment by leongersen** [comment] 2015-07-13 16:01
Could it be that no `mouseup` fires on disabled elements?

-----Original Message-----

**Comment by jgerigmeyer** [comment] 2015-07-13 16:03
Right, exactly.

**Comment by leongersen** [comment] 2015-07-13 16:06
Could you try: `$('[disabled]').on(function(){ $(document).trigger('mouseup'); });`

I'm on my phone at an airport ;)

-----Original Message-----

**Comment by jgerigmeyer** [comment] 2015-07-13 16:16
I don't think you can detect any events on `disabled` elements with JS; most browsers don't even fire them. See discussion here: https://github.com/vitch/jScrollPane/issues/236

For browsers that support `pointer-events`, I think the simplest solution is using CSS:

```css
:disabled { pointer-events: none; }
```

**Comment by jgerigmeyer** [comment] 2015-07-13 16:38
Maybe the best, at least for now, would be to document the potential bug and suggest the CSS approach?

**Comment by jgerigmeyer** [comment] 2015-07-13 18:50
Also: enjoy your vacation! :)

**Comment by rhefner** [comment] 2015-08-07 23:24
Also seeing this, though I don't have any disabled elements that it's hovering over.  Rather, I have two divs, side-by-side.  While dragging on the slider, hover the mouse over the second div to the right.  When the mouse enters the second div (the one without the slider) and comes back in, it stays attached.

Sometimes clicking somewhere in the div with the slider releases it, sometimes it doesn't.

**Comment by Ceremony64** [comment] 2015-09-10 08:15
Related: #509

**Comment by leongersen** [comment] 2015-10-26 14:40
This is (very close to) fixed in noUiSlider 8.1.0. The `end` event is now triggered when a `mousemove` is triggered without a pressed button, so when the cursor leaves the disabled element, the handle is released. This still means the handle responds to movement *within* the `disabled` element, but that seems both a fairly minor issue and, seeing issues elsewhere, practically impossible to solve.

**Closed by leongersen** 2015-10-26 14:40 UTC
Labels: Bug
