### ISSUE TITLE
pips do not update if the range has been updated.

### ISSUE THREAD

**Issue by slankas** [leongersen/noUiSlider#780] opened 2017-04-23 00:59 UTC
To replicate: (code at end)
- Create a nouislider with pips.
- update range values (min and max)
You should see that the pip labels do not change.

Possible fix:
1) In function pips ( grid ), replace the return statement with 
		if (typeof(scope_Target.previousPIPSElement) != 'undefined')  {
			scope_Target.removeChild(scope_Target.previousPIPSElement);
		}
		
		scope_Target.previousPIPSElement = addMarking(spread,filter,	format);
		
		return scope_Target.appendChild(scope_Target.previousPIPSElement);
this will remove the previous markings if present
2) In updateOptions, add this if clause after "valueSet(optionsToUpdate.start || v, fireSetEvent);"
		if ( options.pips ) {
			pips(options.pips);
		}

Replication Code:
	var slider = document.getElementById('slider');
	var theSlider = noUiSlider.create(slider, {
		start: [20, 80],
		connect: true,
		range: {
			'min': 10,
			'max': 100
		},
		pips : {
			mode: 'count',
			density: 4,
			values: 5
		}
	});
	theSlider.updateOptions({
		range: {
			'min' : 50,
			'max' : 500
		}
	})

**Comment by leongersen** [comment] 2017-05-28 08:48
Duplicate of #669.

**Closed by leongersen** 2017-05-28 08:48 UTC
