### ISSUE TITLE
Bug with tooltip on safari

### ISSUE THREAD

**Issue by gotip** [leongersen/noUiSlider#741] opened 2016-12-27 08:52 UTC
In safari Safari 10.0.1 have problem on slider with tooltip. When i click or slider handler, he change color, If color is red change to blue, if blue change to red. I can repeat this bug on plugin home page **"noUiSlider: lightweight JavaScript range slider"**

**Comment by leongersen** [comment] 2016-12-27 13:12
Could you clarify this? I don't understand what you are saying.

**Comment by leongersen** [comment] 2017-01-10 16:04
Closing this for lack of follow up.

**Comment by phpanos** [comment] 2017-01-19 17:56
I think I have a similar issue. My handle is getting some random colors when draging from one value to another. It's almost "flickering". I can reproduce the same type of behaviour in the documentation when dragging the "More than two values" example, where the green color gets another green (lime-ish) color. Also on Safari 10.0.1, Macbook Pro on OSX EL Capitan.

**Comment by leongersen** [comment] 2017-01-19 18:59
I don't have a Mac at hand, so I can't test this myself. Could you try removing `-webkit-tap-highlight-color: rgba(0, 0, 0, 0);` from the CSS and see if that resolves this?

**Comment by phpanos** [comment] 2017-01-19 20:13
I'll get back to you tomorrow when I can try this again. Thanks for the fast reply!

**Comment by phpanos** [comment] 2017-01-20 09:00
I tried to remove that line of code and it didn't help. A little note is that I cannot reproduce this on my Retina screen, only on my thunderbolt display connected to my macbook. So this issue seems to appear on non-retina macbooks on Safari. Also tried this on a macbook air (non-retina) on safari and I got the same issue there.

**Comment by leongersen** [comment] 2017-01-28 15:18
I'm afraid I don't have any of that equipment, so I can't reproduce this issue. Maybe you could file a browser bug if you can reduce it?

**Comment by leongersen** [comment] 2017-02-01 19:39
I'm closing this as this isn't currently actionable and doesn't seem to be an issue in noUiSlider. If you think it is, feel free to comment and I'll reopen this issue.

**Closed by leongersen** 2017-02-01 19:39 UTC
Labels: Unclear
