### ISSUE TITLE
Conflict Prototype.js and noUiSlider : can drag handles on mobile devices

### ISSUE THREAD

**Issue by PierreLeMaguer** [leongersen/noUiSlider#909] opened 2018-08-28 14:03 UTC
Hi,

I'm facing an issue already reported : #908 #902 
The error occurred on mobile device on chrome, we can't drag handles.
```
Uncaught TypeError: this.each is not a function
    at TouchList.findAll (prototype.js:883)
    at G (nouislider.min.js:3)
    at HTMLDivElement.f (nouislider.min.js:3)
```
```
Uncaught TypeError: this.each is not a function
    at TouchList.findAll (prototype.js:883)
    at fixEvent (nouislider.js:1473)
    at HTMLDivElement.method (nouislider.js:1387)
```
Can you have a look on this ?

Thanks.

**Comment by leongersen** [comment] 2018-09-14 08:37
What prototype.js version is this? `TouchList.findAll` does not seem to be in [the latest release (1.7.3)](http://prototypejs.org/download/).

**Comment by binbinwx** [comment] 2018-09-14 08:54
I don't know if magento1.9 will have problems with this version of Prototype.js.

**Comment by leongersen** [comment] 2018-09-14 08:56
I'm not suggesting you upgrade, it's just hard to debug things like this without full details. I'm not familiar with the prototype.js internals, but from the stack trace above it looks like prototype is altering events before they reach noUiSlider.

**Comment by binbinwx** [comment] 2018-09-14 09:05
I still recommend full compatibility with other libraries.
There is still another question I would like to ask you, not about this, the problem is not convenient. I said above, do you have a personal email address?

**Comment by leongersen** [comment] 2018-09-14 09:11
There's an email address on [my GitHub profile](https://github.com/leongersen), but if you have any issues with the library I'd prefer it if you open a new issue.

**Comment by binbinwx** [comment] 2018-09-14 09:16
thank you.

**Comment by laurin1** [comment] 2018-09-17 13:43
> What prototype.js version is this? `TouchList.findAll` does not seem to be in [the latest release (1.7.3)](http://prototypejs.org/download/).

.findAll is an Enumerable method and is in in 1.7.3 (https://github.com/prototypejs/prototype/blob/5fddd3e/src/prototype/lang/enumerable.js#L331) so for that to work with TouchList, that has to be Enumerable: 

http://api.prototypejs.org/language/Enumerable/. 

The error "this.each is not a function" indicates that TouchList is not an Enumerable - either the elements that are being used to build TouchList don't exist (or the method use to access these elements cannot do so).

**Comment by leongersen** [comment] 2018-09-20 13:02
This issue is in this prototype.js line:

```
Object.extend(arrayProto, Enumerable); 
```

If overrides `Array.prototype.find` by a function called `detect`. noUiSlider uses the original `Array.prototype.find`.

**Comment by leongersen** [comment] 2018-09-20 13:09
Stack trace in noUiSlider 12.0.0:

```
Uncaught TypeError: this.each is not a function
    at TouchList.detect (prototype.js:905)
    at fixEvent (nouislider.js?v=1200:1457)
    at HTMLHtmlElement.method (nouislider.js?v=1200:1363)
detect @ prototype.js:905
fixEvent @ nouislider.js?v=1200:1457
method @ nouislider.js?v=1200:1363
```

**Comment by leongersen** [comment] 2018-09-24 05:31
As a workaround, restore the original array find after including prototype.js:

```
    <script>var originalArrayFind = Array.prototype.find;</script>
    <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>
    <script>Array.prototype.find = originalArrayFind;</script>
```

**Comment by sebtb** [comment] 2018-09-25 14:58
Thank you for your work leongersen, will there be a "fix" in nouislider module for that issue?

**Comment by KevinOxwork** [comment] 2018-11-26 15:49
Hello,

Have you find the solution to this problem ? I still have the case

Thanks
Kévin

**Comment by clotted** [comment] 2019-01-01 14:10
> As a workaround, restore the original array find after including prototype.js:
>     <script>var originalArrayFind = Array.prototype.find;</script>
>     <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>
>     <script>Array.prototype.find = originalArrayFind;</script>

This workaround is successful for me using Magento 1.9.3.x and browsing with Safari on iOS 11
Had to update Prototype.js to version 1.7.3
If using Prototype.js 1.7 (bundled with Magento 1.9.3.x) it didn't work.

Hope fix is included in noUISlider release soon.

**Comment by leongersen** [comment] 2019-01-02 14:59
> Hope fix is included in noUISlider release soon.

This is a prototype.js issue; it breaks the array prototype.

**Comment by AndresInSpace** [comment] 2019-04-30 19:25
I simply added:
`
TouchList.prototype.each = Array.prototype.each;
TouchList.prototype._each = Array.prototype._each;
`
to noUislider.min.js at beginning and seems to have fixed my issue(s).
The issue seems to stem from around line 721 where filter/find is overwritten by prototype.js, it doesn't hang up for me here.. but on the prototype extended method of filter/find calling this.each/this._each on the passed l var (TouchList).
`if ("touchstart" === t.type) {
                            var u = Array.prototype.filter.call(t.touches, l);
                            if (1 < u.length)
                                return !1;
                            n = u[0].pageX,
                            i = u[0].pageY
                        } else {
                            var c = Array.prototype.find.call(t.changedTouches, l);`

**Comment by manelaguayo** [comment] 2019-06-07 10:09
I simply added:

TouchList.prototype.each = Array.prototype.each;
TouchList.prototype._each = Array.prototype._each;

to noUislider.min.js at beginning and seems to have fixed my issue(s).

**Comment by leongersen** [comment] 2020-05-11 15:56
I'm closing this as there is nothing to fix within noUiSlider and a workaround is available.

**Closed by leongersen** 2020-05-11 15:56 UTC
Labels: Support

**Comment by adamchipperfield** [comment] 2021-08-09 10:17
I'm still having this issue, despite the workaround. Any ideas?
