### ISSUE TITLE
Add config to provide any attribute property

### ISSUE THREAD

**Issue by jeffj6123** [leongersen/noUiSlider#1085] opened 2020-07-01 16:52 UTC
Ive noticed a few issues that have been raised mainly in regards to accessibility related issues, which seems to be related to adding specific aria attributes to the sliders.

It might be good to add a dictionary of <attribute name, value> config for each slider control. This would let people add whichever properties are necessary for their compliance.

Now im not sure how if this would work for using updateOptions. You say in the documentation this only works for certain config options

**Comment by leongersen** [comment] 2020-07-17 07:49
I think this could be solved by using an `update` event listener, and changing/setting any attributes on the handles. What aria attributes are you missing? The slider currently implements the WAI-ARIA roles as defined in [this spec](https://www.w3.org/TR/wai-aria-practices/#slidertwothumb).

**Comment by LeCodeCo** [comment] 2021-04-25 14:48
This issue is a duplicate of #1019

**Comment by leongersen** [comment] 2021-05-04 09:50
@LeCodeCo Yes, it is. I'll close this one.

**Closed by leongersen** 2021-05-04 09:50 UTC
Labels: Feature

**Comment by leongersen** [comment] 2021-05-04 09:52
Duplicate of #1019
