### ISSUE TITLE
Update options on resize

### ISSUE THREAD

**Issue by JordanSayner** [leongersen/noUiSlider#713] opened 2016-10-28 13:58 UTC
Hello,

I am trying to change my slider form horizontal to vertical when resizing, my script i have is 

```
       // Use the conventional $ prefix for variables that hold jQuery objects.
        var budgetSlider = document.getElementById('budget-slider');

        // If the only purpose of the windowWidth() function is to set the slide variables,
        // it can be renamed and rewritten to supply the full configuration object instead.
        function buildSliderConfiguration() {
            // When possible, you should cache calls to jQuery functions to improve performance.
            var windowWidth = $(window).width();
            var orientation;

            if (windowWidth < 768) {
                orientation = 'vertical';
            }
            else {
                orientation = 'horizontal';
            }

            return {
                orientation: orientation,
            };
        }

        // This function can be called either to initialize the slider for the first time
        // or to reload the slider when its size changes.
        function configureSlider() {
            var config = buildSliderConfiguration();

            console.log(config)

            //$(budgetSlider).noUiSlider.destroy();

            noUiSlider.create(budgetSlider, {
                start: [4, 6],
                connect: true,
                step: .5,
                tooltips: [wNumb({ decimals: 1, prefix: '£' }), wNumb({ decimals: 1, prefix: '£', postfix: 'k' })],
                margin: 1,
                config,
                range: {
                    'min': [1],
                    'max': [15]
                }
            }, true);
        }

        // Configure the slider every time its size changes.
        $(window).on("orientationchange resize", configureSlider);
        // Configure the slider once on page load.
        configureSlider();
```

but i keep getting the following error

> Uncaught Error: Slider was already initialized.(…)

not really sure how to overcome this, so any help would be greatly appreciated.

**Comment by leongersen** [comment] 2016-10-28 14:47
You have this line commented out: `$(budgetSlider).noUiSlider.destroy();`.

You could do:
```
if ( budgetSlider.noUiSlider ) { budgetSlider.noUiSlider.destroy(); }
```

**Comment by JordanSayner** [comment] 2016-10-28 15:20
Hi,

That line was commented out as it wasn't working.

I have added the if statement you suggested, no longer getting the console error, but the config option isn't updating.

i have added a console.log within the if statement and that is firing.

I have tried loading the screen < 768 to load vertically but that doesn't work either. It still loads horizontal

**Comment by JordanSayner** [comment] 2016-10-28 15:49
https://jsfiddle.net/LordJording/hh2qwo39/2/

Here is a quick demo i have set up.

**Comment by leongersen** [comment] 2016-10-29 14:33
I don't know why you'd expect the `config` variable to be merged into the options you pass to the slider (that's not how objects work, I'm afraid) but that's were the problem is. I've updated the fiddle:

https://jsfiddle.net/hh2qwo39/3/

**Comment by JordanSayner** [comment] 2016-10-31 08:23
Awesome, thanks. works perfect

**Closed** 2016-10-31 08:23 UTC
Labels: Support
