### ISSUE TITLE
Firefox 40, noUiSlider inside iframe, if you mousedown to drag a slider then move the mouse out of the iframe the slider get stuck following the pointer and can't be released

### ISSUE THREAD

**Issue by GiacomoP** [leongersen/noUiSlider#543] opened 2015-10-30 12:11 UTC
Only on Firefox (Chrome and Opera work fine).

1 - Simple slider, set to "snap" behaviour.
2 - Slider in a page embedded in another page through an iframe.
3 - Mousedown on the slider to drag it left and right without the pointer leaving the iframe, release the mouse, slider works fine.
4 - Mousedown on the slider, drag it outside the iframe, mouseup outside the iframe with the slider. Now if the pointer goes back inside the iframe the slider will follow it, but it's impossible to fix the slider in a certain position. Click does not fix it, the slider will always follow the pointer.

On other browsers, the slider doesn't get "stuck" following the mouse pointer, if you mouseup outside the iframe it'll get fixed to the last position it was in.

**Comment by leongersen** [comment] 2015-10-30 12:57
What version are you using? 8.1.0 has some changes that should fix this.

**Comment by GiacomoP** [comment] 2015-10-30 13:04
Hi ya, great library by the way!

The version should be the latest 8.1.0

`/*! nouislider - 8.1.0 - 2015-10-25 16:05:43 */`

**Comment by leongersen** [comment] 2015-10-30 13:27
That's the latest version alright. Can you set up a minimal example, I'll play with it a little.

**Comment by GiacomoP** [comment] 2015-10-30 13:45
Of course, here: http://home.mysmark.com/temp/

At least on Firefox 40 and 41, too, I just updated it.

**Comment by GiacomoP** [comment] 2015-10-30 18:23
Referencing #509

**Comment by leongersen** [comment] 2015-10-31 18:43
I'll have a look!

**Comment by leongersen** [comment] 2015-10-31 18:53
This is caused by [this FireFox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1048294). I'll see about a workaround.

**Comment by TanaseButcaru** [comment] 2015-11-03 20:46
I can confirm this bug in Firefox 41.0.2 (Linux), Chromium (Linux) and also on a freshly installed Opera browser (Linux).

The bug only triggers after dragging the slider. Normal slider change via tap/click is working fine.

Just updated to 8.1.0 from 8.0.2 where I haven't experienced this issue.

**Comment by Ceremony64** [comment] 2015-11-05 14:00
the ff bug youre refering to isn't really a bug:
> "which" was introduced by Microsoft (IE specific quirk) and is to this day not an official web standard (or standardized for that matter) or even properly documented. Firefox simply mimics the original culprits behavior perfectly: IE also has which = 1 on mouseover.
> In other words, the correct implementation of this feature/bug can be seen in both IE and Firefox and Chrome is the one that differs from the rest.

also, bug persists in IE9 as well (via the alt+tab method). IE10+ seems fine.

**Comment by leongersen** [comment] 2015-11-05 18:35
I'm considering it a bug, because [MDN says](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which) `1` means `left button`. If that isn't intended, they should mention it in the docs. The `button` property has the same problem.

**Comment by Nihilivin** [comment] 2015-11-06 19:09
This bug seems to be avoidable by `behaviour: "tap"` instead of `behaviour: "snap"` or other. I know this is not a bugfix, but it seems that the problem is related with event snap (/src/js/options.js l.180)
Even when the bug happens, a simple click detach the handler from the mouse pointer. Maybe comparing end events for "snap" and "tap" behaviour can help...

**Comment by leongersen** [comment] 2015-11-06 19:40
This doesn't have anything to do with `snap`. The example shows it happening without that option. The problem is the state of the `buttons`, `which` and `button` properties not being consistent across browsers. The fix for IE9 messed up Firefox in this case. The reason we're discussing the Firefox 'bug' is because, in my opinion, the MDN docs should be correct.

**Comment by Nihilivin** [comment] 2015-11-06 22:21
Oh, yeah, indeed.... However, I found a sort of fix... Not the most beautiful fix I've ever made, but it works. It simply kill the event catching on document.mouseout . I've made a pull-request here https://github.com/leongersen/noUiSlider/pull/555

**Comment by NocheVolta** [comment] 2015-11-18 04:59
On Firefox 42.0 OS X the bug seems disappear, I was suffering some days ago with it but now I can't reproduce it :)

**Comment by ghemad** [comment] 2015-11-26 07:03
HI Leongersen ,

Could you please tell me what was the exact fix for this issue? I can't update the nouiSlider.js as in my case it is coming from the Theme.
Thanks,
Suraj

**Comment by leongersen** [comment] 2015-11-26 07:34
I think I figured this out, will patch it this week. For reference, the [issue is here](https://github.com/leongersen/noUiSlider/blob/606ead30046e579237674c65ddab7cc9dfba9e0f/src/js/scope_events.js#L49).

**Comment by leongersen** [comment] 2015-11-29 14:56
This should now be fixed.

**Closed by leongersen** 2015-11-29 14:56 UTC
Labels: Bug, inDev
