### ISSUE TITLE
IE8 event.calcPoint = NaN

### ISSUE THREAD

**Issue by RyKilleen** [leongersen/noUiSlider#554] opened 2015-11-06 21:25 UTC
I can't seem to narrow this one down very well, but on IE 8 we're experiencing a failure when trying to manually move the slider. 

In the function tap, event.calcPoint == NaN so location, and eventually 'to', also equal NaN. This causes the slider to bottom out. Please note that the most recent polyfill.io is included. I should also mention that knockout 3.3 and jquery 1.10 are also included, though  they don't appear to be interfering.

**Comment by leongersen** [comment] 2016-12-10 18:41
I'm not very interested in supporting IE8 anymore (as I don't have any device that can natively use it and usage outside of China is negligible), but I couldn't reproduce this at the time. If there's any more input on this, feel free to comment and I'll re-open this issue. Closing for now as there is nothing actionable.

**Closed by leongersen** 2016-12-10 18:41 UTC
Labels: Unclear
